- name: list uptime
# To run only against a group defined in Tower inventory choosen to run this template
#  hosts: Linux
  hosts: all
  remote_user: root

  tasks:
    - name: List uptime
      shell: "echo ; hostname; echo ; uptime"
      register: uptime

    - debug: 
        var: uptime.stdout_lines

    - name: Dump vars to /tmp/{{ inventory_hostname }}.facts
      delegate_to: localhost
      run_once: true
      copy:
        content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
        dest: "/tmp/all.facts"
#      with_items:
#        - "{{ hostvars[inventory_hostname] }}"

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      register: fct
#      tags: debug_info


    - name: Install packages
      yum: 
        name: "{{ rpms }}"
        state: present
      vars:
        rpms:
          - iperf3
          - git
          - jnettop
      when: ansible_distribution == "CentOS"       
